---

- name: Arista Ansible testing
  hosts: arista

  tasks:
    - name: create kb4 VLAN
      ex3_ansible_vlan: vlan_id=224 vlan_name=kb4
            eapi_username={{ eapi_username}} 
            eapi_password={{ eapi_password }} 
            eapi_hostname={{ eapi_hostname }} 
            eapi_port={{ eapi_port }}

