---

# Use Ansible to configure your 'primary Ethernet interface' as follows:
#
# interface description:    *** IN USE ***
# switchport mode:          access
# VLAN:                     <one of the VLANs created in exercise1>
#

- name: Arista-Ansible Exercise2
  hosts: arista

  tasks:
    - name: Setting Ethernet3 description
      eos_interface: name=Ethernet3 description="*** IN USE ***"
            eapi_username={{ eapi_username}} 
            eapi_password={{ eapi_password }} 
            eapi_hostname={{ eapi_hostname }} 
            eapi_port={{ eapi_port }}

    - name: Set Ethernet3 to access mode, VLAN222
      eos_switchport: name=Ethernet3 mode=access access_vlan=222 trunk_allowed_vlans=all
            eapi_username={{ eapi_username}}
            eapi_password={{ eapi_password }}
            eapi_hostname={{ eapi_hostname }}
            eapi_port={{ eapi_port }}

